# Generated by Django 4.2.5 on 2023-09-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangun_app', '0003_post_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region_certification',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
