# Generated by Django 4.2.5 on 2023-09-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangun_app', '0004_userprofile_region_certification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='product_reserved',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='product_sold',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
