# Generated by Django 4.2.5 on 2023-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangun_app', '0005_alter_post_options_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
