# Generated by Django 4.2.5 on 2023-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangun_app', '0010_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
