# Generated by Django 4.2.5 on 2023-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangun_app', '0012_chatroom_message_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='latest_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
