# Generated by Django 4.2.5 on 2023-09-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangun_app', '0014_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='dangun_app.post'),
        ),
    ]
