# Generated by Django 4.2.5 on 2023-10-03 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dangun_app', '0015_chatroom_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
